### ISSUE TITLE
Failed to fetch models [Custom OpenAl -compatible APis]

### ISSUE THREAD

**Issue by lovejavaee** [XInTheDark/raycast-g4f#171]
When add custom API under `Preferences` -> [Manage APIs] `Custom OpenAl -compatible APis` -> `Add custom APl...`
JSON parse error, show `syntaxError Unexpected non-whitespace character`

**To Reproduce**
1. Go to 'Preferences'
2. Click on 'Custom OpenAl -compatible APis'
3. Click on 'Add custom APl...'
4. Custom OpenAl -compatible API as normal
5. When click `Save` button, see error

**Expected behavior**
Custom OpenAl -compatible APis as expect.

**Screenshots/Recordings**
<img width="862" alt="image" src="https://github.com/user-attachments/assets/8e118ba9-fa63-453f-b223-7ac30c45d29d" />
![image](https://github.com/user-attachments/assets/841500ce-732a-4203-84fa-c8a0b6b5d2db)

**Information**
 - raycast-g4f version: [e.g. v5.0]
 - Raycast version: [e.g. v1.88.4]

**Additional context**
```17:09:01 SyntaxError: Unexpected non-whitespace character after JSON at position 4
    at JSON.parse (<anonymous>)
    at _Response.json (/Users/xxx/.config/raycast/extensions/raycast-g4f/preferences.js:6011:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getOpenAIModels (/Users/xxx/.config/raycast/extensions/raycast-g4f/preferences.js:34337:17)
    at async onSubmit (/Users/xxx/.config/raycast/extensions/raycast-g4f/preferences.js:34845:26)
    at async /Applications/Raycast.app/Contents/Resources/RaycastNodeExtensions_RaycastNodeExtensions.bundle/Contents/Resources/api/node_modules/@raycast/api/index.js:20:6111
```

**Comment by XInTheDark** [comment]
Hey, can you check if the Ollama server is currently running? The extension needs to fetch the list of models, so the endpoint will need to be accessible when you add it.

**Comment by lovejavaee** [comment]
Ollama is running

Same with cloud API, like Groq or Sambanova

**Comment by XInTheDark** [comment]
Could you provide the response when you go to `{Your API Base URL}/models` in the browser? e.g. `http://localhost:11434/models"

**Comment by lovejavaee** [comment]
http://localhost:11434/models ->  `404 page not found`

However, according ollama doc, List Local Models endpoint should be [/api/tags](https://github.com/ollama/ollama/blob/main/docs/api.md#list-local-models)

http://localhost:11434/api/tags return valid models JSON.

**Comment by XInTheDark** [comment]
Hi, can you try changing the base URL to http://localhost:11434/v1 ? That seems to be the OpenAI-compatible endpoint.

**Comment by lovejavaee** [comment]
http://localhost:11434/v1/models 
return valid current running models JSON.

**Comment by XInTheDark** [comment]
Hi @lovejavaee, can you check if the issue is fixed now? I've added an option to manually set the models for the endpoint.

**Comment by lovejavaee** [comment]
Great! Manually set the models work well for Sambanova AI.

However following Issue still remains.

`Add Local Ollama to Custom OpenAl -compatible API work, but when you choose Ollama for default provider, chat still return JSON parse error:
SyntaxError: Unexpected non-whitespace character after JSON at position 4
`
